In [ ]:
x="SARAS"
i=0
while(i<len(x)):
  print(i,x[i])
  i+=1

In [ ]:
var = "sarty"
index=0
end=4
while(index < len(var)):
    print(index, var[index], end, var[end] )
    index+=1
    end-=1

In [98]:
var = "sarts"
index=0
end= len(var)-1
a=False
while(index < len(var)):
  if( var[index] != var[end]):
    a=True
    break

  index+=1
  end-=1

if(a==True):
  print("not palindrome")
else:
  print("palindrome")

not palindrome


In [99]:
a=False
for i in range(2,8):
  if(i==6):
    a=True
    break
  print(i)
print(a)

2
3
4
5
True


In [100]:
num=9
i=2
while(i<num):


SyntaxError: incomplete input (ipython-input-3632380415.py, line 3)

In [101]:
# import numpy
! pip install numpy
import numpy as np


In [102]:
li=[1.0,2,3,4,5]
arr=[]
for num in li:
  arr.append(int(num))
print(arr)


[1, 2, 3, 4, 5]


In [103]:
for num in li:
  print(type(num))

<class 'float'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [104]:
a=np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [105]:
# 2d array using 2d list

np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
# 3d array using the 3d list
np.array([[[1,2,3]]])

array([[[1, 2, 3]]])

In [107]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [108]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [109]:
c=np.zeros((4,5))
c.shape

(4, 5)

In [110]:
c.ndim

2

In [111]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [112]:
np.ones((5,6),dtype=str)

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [113]:
np.eye(5) # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [114]:
# arange function creats an array in range (start,end,step) --> exclusive
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [116]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [117]:
np.linspace(10,20,5)   # stop inclusive

array([10. , 12.5, 15. , 17.5, 20. ])

In [118]:
st='False'
bool(st)

True

In [119]:
a=np.linspace(10,20,12).reshape(3,4)
print(a)

b=np.linspace(30,40,12).reshape(3,4)
print(b)

a+1

[[10.         10.90909091 11.81818182 12.72727273]
 [13.63636364 14.54545455 15.45454545 16.36363636]
 [17.27272727 18.18181818 19.09090909 20.        ]]
[[30.         30.90909091 31.81818182 32.72727273]
 [33.63636364 34.54545455 35.45454545 36.36363636]
 [37.27272727 38.18181818 39.09090909 40.        ]]


array([[11.        , 11.90909091, 12.81818182, 13.72727273],
       [14.63636364, 15.54545455, 16.45454545, 17.36363636],
       [18.27272727, 19.18181818, 20.09090909, 21.        ]])

In [120]:
c=np.array([1,2,3,4])

c ** 2

array([ 1,  4,  9, 16])

In [121]:
np.arange(20,100).reshape(10,8)

array([[20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51],
       [52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67],
       [68, 69, 70, 71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80, 81, 82, 83],
       [84, 85, 86, 87, 88, 89, 90, 91],
       [92, 93, 94, 95, 96, 97, 98, 99]])

In [122]:
li=[1,2,3,4]
a=np.array(li)
a

array([1, 2, 3, 4])

In [123]:
# creating 1d array using the list comprehension
a=[i for i in range(1,101) ]
b=np.array(a)

# for checking the dimension of the array (.ndim)
print(b.ndim)



1


In [124]:
# created 2d array using the 2d list
li=[[1,2,3],[4,5,6],[7,8,9]]
c=np.array(li)
print(c)

# checking the shape of the data (row and columns)

print(c.shape)

# checking the dimension of the data

print(c.ndim)


# checking the size of the data

print(c.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9


In [125]:
li=[[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11],[10,11,12,13,14],[13,14,15,16,17]]
k=np.array(li)
print(k)

print(k.shape)
print(k.size)
print(k.ndim)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [10 11 12 13 14]
 [13 14 15 16 17]]
(5, 5)
25
2


In [126]:
# this function is responsible for the creating an nd array of ones (1 is initialised to all the elements or positions to the matrix)

# for explicitely converting the data type of the matrix we use dtypes as an argument

np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [127]:
# this function is responsible for initialising the 0 to  all the position into the matrix
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [128]:
# arange is use to create an array with in a given range and
# start index ==> inclusive
# end index ==> Exclusive
# step ==> to jump the values of the range
# reshape is use to reshape the array into this we would pass rows numbers and columns
# the rows and columns product should be the total no elements(.size)
d=np.arange(1,101)
e=d.reshape(10,10)
print(e)
print(d.size)
print(e.size)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
100
100


In [129]:
# matrix
# why use matrix
# matrix operations
# what is the use of matrix operations into the machine learning

In [130]:
'''
What is matrix ==>

A matrix is a table of numbers arranged in rows and columns.

Uses of Matrices

Mathematics

Computer science

Machine learning

Data science

3D graphics

Solving linear equations

'''

'\nWhat is matrix ==>\n\nA matrix is a table of numbers arranged in rows and columns.\n\nUses of Matrices\n\nMathematics\n\nComputer science\n\nMachine learning\n\nData science\n\n3D graphics\n\nSolving linear equations\n\n'

In [131]:
'''
Why use  matrix ==>
✅ 1. To represent large data easily

A matrix arranges data in rows and columns, just like a table.

✅ 2. To solve systems of linear equations

✅ 3. Used everywhere in computer science

Graphics

Image processing

Machine learning models

Neural networks

Data transformations

All these use matrices internally.

✅ 4. For 3D transformations

Matrices are used to:

Rotate objects

Move objects

Scale objects
in computer graphics and animation.

✅ 5. In Data Science & AI

Datasets are stored as matrices, and algorithms (like linear regression, deep learning) use matrix operations for speed.

✅ 6. For encryption and coding theory

Matrices help to encode and decode secret messages.

⭐ Simple Summary

Matrix = a powerful tool to store and process large sets of numbers quickly and efficiently.
'''

'\nWhy use  matrix ==>\n✅ 1. To represent large data easily\n\nA matrix arranges data in rows and columns, just like a table.\n\n✅ 2. To solve systems of linear equations\n\n✅ 3. Used everywhere in computer science\n\nGraphics\n\nImage processing\n\nMachine learning models\n\nNeural networks\n\nData transformations\n\nAll these use matrices internally.\n\n✅ 4. For 3D transformations\n\nMatrices are used to:\n\nRotate objects\n\nMove objects\n\nScale objects\nin computer graphics and animation.\n\n✅ 5. In Data Science & AI\n\nDatasets are stored as matrices, and algorithms (like linear regression, deep learning) use matrix operations for speed.\n\n✅ 6. For encryption and coding theory\n\nMatrices help to encode and decode secret messages.\n\n⭐ Simple Summary\n\nMatrix = a powerful tool to store and process large sets of numbers quickly and efficiently.\n'

In [132]:
'''
Matrix Operations ==>

Operation	                                    Meaning
Addition	                                    Add elements
Subtraction                                  	Subtract elements
Scalar Multiplication	                        Multiply each element by a number
Matrix Multiplication                        	Row × Column
Transpose                                    	Rows become columns
Determinant                                 	Single number representing matrix
Inverse	                                      Used to solve equations

'''

'\nMatrix Operations ==>\n\nOperation\t                                    Meaning\nAddition\t                                    Add elements\nSubtraction                                  \tSubtract elements\nScalar Multiplication\t                        Multiply each element by a number\nMatrix Multiplication                        \tRow × Column\nTranspose                                    \tRows become columns\nDeterminant                                 \tSingle number representing matrix\nInverse\t                                      Used to solve equations\n\n'

In [133]:
# using list
import numpy as np
li=[[1,2,3],[4,5,6],[7,8,9]]
np.array(li)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
# using linspace
np.linspace(10,20,5)

# (20-10)/5-1 --> 10/4 --> 2.5
# max - min/ n-1 --> space

array([10. , 12.5, 15. , 17.5, 20. ])

In [135]:

np.linspace(10,20,6).reshape(3,2)

array([[10., 12.],
       [14., 16.],
       [18., 20.]])

In [136]:
# using arange ==>
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [137]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [138]:
# Accessing the elements using the indicess of the array is known indexing
# 0-based indexing -> it the index should starts from 0
#  array_name[index]
a=np.array([1,2,3,4,5])
a[3]

np.int64(4)

In [139]:
a=np.array([1,2,3,4,5])
a[-1]

np.int64(5)

In [140]:
# you have to print the numbers of the araay using the negative indexing
a=np.array([1,2,3,4,5])
for i in range(1,len(a)+1):
  print(a[-i])


5
4
3
2
1


In [141]:
a=np.array([1,2,3,4,5])
for i in range(-5,0):
  print(a[i])

1
2
3
4
5


In [142]:
# slicing is used to find or extract the subarray from given array
# bydefault the starting index is 0
# bedefault the ending index is len(array)-1
# step by default = 1
a=[1,2,3,4,5]
a[1:4]

[2, 3, 4]

In [143]:
# generate an array using the arange function from 1,100 using 3 steps print all the elements of the array

a=np.arange(1,101,3)
print(a)

[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100]


In [144]:
# using slicing reversing the array
array = np.array([1,2,3,4,5])
array[::-1]

array([5, 4, 3, 2, 1])

In [145]:
# matrix -> [rows],[element index]
matrix=np.arange(1,13).reshape(3,4)
print(matrix[0][0])

1


In [146]:
import numpy as np
matrix=np.arange(1,13).reshape(3,4)
for i in range(0,3):
  for j in range(0,4):

    print(matrix[i][j],end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [147]:
# slicing on the matrices and vectorisation


In [148]:
# 3d array using 3d list

In [149]:
matrix=np.arange(1,13).reshape(3,4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [150]:
matrix[0]

array([1, 2, 3, 4])

In [151]:
matrix[1]

array([5, 6, 7, 8])

In [152]:
matrix[2]

array([ 9, 10, 11, 12])

In [153]:
# in matrix slicing we use the slicing the exteact the sub matrix
# matrix_name[slicing_row,slicing_column]
matrix[0,:]

array([1, 2, 3, 4])

In [154]:
matrix[1,:]

array([5, 6, 7, 8])

In [155]:
matrix[:,0]

array([1, 5, 9])

In [156]:
matrix[:,1]

array([ 2,  6, 10])

In [157]:
# finding the first two columns of the matrix
# matrix[:] --> it will access whole rows
# matrix[:,0:2] --> this will give the first two columns
matrix[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [158]:
matrix[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [159]:
matrix[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [160]:
# random number generate ==>
# in numpy the random module is used to generate the random number
# randint ==> it generate an array in given range , into which we can give number of element
np.random.randint(1,10,10)

array([7, 9, 5, 5, 2, 5, 2, 5, 4, 3])

In [161]:
np.random.seed(12)     #np.random.seed(--) ==>
np.random.randint(1,10,10)

array([7, 2, 3, 4, 4, 1, 7, 2, 5, 6])

In [162]:
# np.random.rand is used to generate the values between 0 to 1
# into this function or method we pass the numbers or element which we want to generate
np.random.rand(40)

array([0.03342143, 0.95694934, 0.13720932, 0.28382835, 0.60608318,
       0.94422514, 0.85273554, 0.00225923, 0.52122603, 0.55203763,
       0.48537741, 0.76813415, 0.16071675, 0.76456045, 0.0208098 ,
       0.13521018, 0.11627302, 0.30989758, 0.67145265, 0.47122978,
       0.8161683 , 0.28958678, 0.73312598, 0.70262236, 0.32756948,
       0.33464753, 0.97805808, 0.62458211, 0.95031352, 0.76747565,
       0.82500925, 0.4066403 , 0.45130841, 0.40063163, 0.99513816,
       0.17756418, 0.9625969 , 0.41925027, 0.42405245, 0.46314887])

In [163]:
# avearage
# li=[1,2,3,4]
# sum(li)/len(li)

s=np.array([1,2,3,4])
np.mean(s)

np.float64(2.5)

In [164]:
# find median
n=np.array([1,2,3,4,5])
np.median(n)

np.float64(3.0)

In [165]:
n=np.array([1,2,3,4,5,6])
np.median(n)

np.float64(3.5)

In [166]:
n=np.array([5,8,9,6,3])
np.median(n)

np.float64(6.0)

In [167]:
n=np.array([5,8,9,6,3,8])
np.median(n)

np.float64(7.0)

In [168]:
# flatten method ==> is used to put all the elements into the one array
m=np.random.randint(1,10,12).reshape(3,4)
print(m)
flatten_matrix=m.flatten()
print(flatten_matrix)

[[2 5 6 4]
 [6 1 3 7]
 [5 8 7 3]]
[2 5 6 4 6 1 3 7 5 8 7 3]


In [169]:
flatten_matrix[0]=5
m

array([[2, 5, 6, 4],
       [6, 1, 3, 7],
       [5, 8, 7, 3]])

In [170]:
n=m.ravel()
n[0]=100
m

# difference beteen the flatten and ravel ==>
# flatten creats a copy of the original matrix into the array
# whenever we change any value of the new array it would not effect on the original
# ravel creates a views of original matrix and into the whenever we change into the new array it will effect the orifinal matrix

array([[100,   5,   6,   4],
       [  6,   1,   3,   7],
       [  5,   8,   7,   3]])

In [171]:
# generate a matrix using random module randint , last columns
matrix = np.random.randint(1,10,12).reshape(3,4)
print(matrix)
print(matrix[:,2:])

[[4 3 7 5]
 [6 1 1 6]
 [5 1 4 8]]
[[7 5]
 [1 6]
 [4 8]]


In [172]:
# 2d elements -> mean -> flatten -> mean
s=np.random.randint(1,10,12).reshape(3,4)
print(s)
flatten_matrix=s.flatten()
print(flatten_matrix)
np.mean(flatten_matrix)

[[7 9 7 2]
 [5 7 6 3]
 [5 1 9 5]]
[7 9 7 2 5 7 6 3 5 1 9 5]


np.float64(5.5)

In [173]:
import numpy as np

arr=np.random.randint(1,11,10)
print(arr)

indices=[1,4,7]
arr1=[]
for i in indices:
  arr1.append(arr[i])

np.array(arr1)


[5 4 8 4 7 2 5 4 9 9]


array([4, 7, 4])

In [174]:
# fancy indexing ==> is a technique in programming , especially in numoy , that allows you to select multiple elements from an array
# at once using a list or array of indices

In [175]:
# here we are performing the fancy indexing
# ==> we give the multiple indices of the elements whichever we want in list
arr[[1,4,7]]

array([4, 7, 4])

In [176]:
arr=np.arange(1,11)
                    # here we creting the view of the original array
view_arr=arr.view()
                    # here we are changing the first element of the duplicated array
view_arr[0]=100
print("original array:",arr)
print("duplicate array:",view_arr)

# view is a method which copies the reference of the original object or arr whenever we want to change anything into the duplicate array
# then it would effect on the original array

original array: [100   2   3   4   5   6   7   8   9  10]
duplicate array: [100   2   3   4   5   6   7   8   9  10]


In [177]:
arr=np.arange(1,11)
copy_arr=arr.copy()

copy_arr[1]=20
print(arr)
print(copy_arr)

# this copy() method is used to copy the object and create actual object at different location
# into this original object is not effected when we change the copied duplicated array

[ 1  2  3  4  5  6  7  8  9 10]
[ 1 20  3  4  5  6  7  8  9 10]


In [178]:
# the numpy.where() function is a powerful tool  for conditional selection and replacement of element within numpy array
arr = np.arange(20,41)
# np.where function or method is used to find the indices on the basic of some condition
np.where(arr>25,'high','low')


array(['low', 'low', 'low', 'low', 'low', 'low', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high'], dtype='<U4')

In [179]:
arr[arr>35]

array([36, 37, 38, 39, 40])

In [180]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
np.vstack([arr1,arr2,arr3])
# vstack => vertical stacking is used to stack the array into the stack formate vertically

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [181]:
# take an array from ranging between 10 to 35
# 18< child
# 18 > adault

arr=np.arange(10,36)
print(arr)
np.where(arr>18 ,'adault','child')

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35]


array(['child', 'child', 'child', 'child', 'child', 'child', 'child',
       'child', 'child', 'adault', 'adault', 'adault', 'adault', 'adault',
       'adault', 'adault', 'adault', 'adault', 'adault', 'adault',
       'adault', 'adault', 'adault', 'adault', 'adault', 'adault'],
      dtype='<U6')

In [182]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
np.hstack([arr1,arr2,arr3])
# hstack==> horizental stacking is used stack the elements or the arr horizentally.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
matrix=np.arange(1,13).reshape(3,4)

arr = np.array([1,2,3]).reshape(3,1)

print(matrix)

print(arr)

print(np.hstack([matrix,arr]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]]
[[ 1  2  3  4  1]
 [ 5  6  7  8  2]
 [ 9 10 11 12  3]]


In [184]:
import numpy as np
arr=np.array([1,2,3,4])
arr
arr+4

array([5, 6, 7, 8])

In [185]:
arr*4

array([ 4,  8, 12, 16])

In [186]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr1+arr2

array([ 6,  8, 10, 12])

In [187]:
matrix=np.arange(1,13).reshape(3,4)
print(matrix+1)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [188]:
matrix=np.arange(1,13).reshape(3,4)
print(matrix)
arr=np.array([1,2,3,4])
print(arr)
print(matrix+arr)
# addition is performing on basis of axis=0 , it means all the elements of the array is added with each row the matrix

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In [189]:
# broadcasting rule ==> broadcasting in numpy is a powerful mechanim that allows arithmetic operations on array of different shape and size

# 1. Dimension Padding: If the two arrays have different numbers of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
# 2. Dimension Compatibility: Two dimensions are considered compatible if they are either:
# --> they are equal in size
# --> one of them has a size of 1

# 3. Error Condition: If in any dimension the sizes disagree and neither is equal to 1, a ValueError exception is raised, and broadcasting cannot occur.

In [190]:
mat1=np.arange(1,10).reshape(3,3)
mat2=np.arange(10,19).reshape(3,3)
print(mat1)
print(mat2)
print(mat1+mat2)
# according to the rule no. 1 of the broadcasting . the dimensions of both matrices have same dimensions.


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [191]:
print(mat1*mat2)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [192]:
mat1=np.arange(1,13).reshape(3,4)
arr=np.array([1,2,3]).reshape(3,1)
print(mat1)
print(arr)
print(mat1+arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]]
[[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]


In [193]:
# 1. Create a 1D NumPy array containing numbers from 5 to 50 with a step of 5.
arr=np.arange(5,51,5)
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [194]:
# 2. Create a 2D array of shape (4, 3) filled with ones.
arr=np.ones((4,3),dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [195]:
# 3. Create an array of 6 equally spaced values between 0 and 1.
arr=np.linspace(0,1,6)
arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [196]:
# 4. Create a 3×3 identity matrix.
matrix=np.eye(3,dtype=int)
matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [197]:
# 5. Find the shape, size, number of dimensions, and data type of a given array.
print(matrix.shape)
print(matrix.size)
print(matrix.ndim)
print(type(matrix))

(3, 3)
9
2
<class 'numpy.ndarray'>


In [198]:
# 6. Convert the Python list [10, 20, 30, 40, 50] into a NumPy array.
list=[10,20,30,40,50]
arr=np.array(list)
arr

array([10, 20, 30, 40, 50])

In [199]:
# 7. Reshape a 1D array of 16 elements into a 4×4 matrix.
arr=np.arange(1,17)
new=arr.reshape(4,4)
new

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [200]:
# 8. Flatten a 2D array into 1D using both flatten() and ravel(). Observe the difference.
arr=np.arange(1,17).reshape(4,4)
flat=arr.flatten()
print(flat)
rav=arr.ravel()
print(rav)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [201]:
# 9. Access the middle element of a 1D array.
arr=np.array([1,2,3,4,5])
np.median(arr)

np.float64(3.0)

In [202]:
# 10. Reverse a NumPy array without using loops.
arr=np.arange(1,13)
arr[::-1]

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [203]:
# 11. Extract all even-indexed elements from a NumPy array.
arr=np.arange(1,13)
arr[::2]

array([ 1,  3,  5,  7,  9, 11])

In [204]:
# 12. Extract the last column from a 2D array.
arr=np.arange(1,10).reshape(3,3)
arr[:,2]

array([3, 6, 9])

In [205]:
# 13. Slice a 1D array to get alternate elements starting from index 1.
arr=

SyntaxError: invalid syntax (ipython-input-327227507.py, line 2)

In [ ]:
# pandas ==> pandas is a library which is used to manipulate the data and analys the data
# pandas is built on the top of numpy library

In [206]:
import pandas as pd
# to read the csv files we use the read_csv method
# read_csv ('path_of_file')
pd.read_csv('/content/sample_data/mnist_test.csv')

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [ ]:
# pandas have two different data types
# 1. series ==> a series is a primary data structure thst is built on top of numpy array
# a pandas series is a one
# 2. dataframe

In [207]:
import numpy as np

In [208]:
# created series with the help of numpy array
pd.Series(np.array([1,2,3,4]))

0    1
1    2
2    3
3    4
dtype: int64

In [209]:
pd.Series(np.array([1,2,3,4]),index=['a','b','c','d'])

a    1
b    2
c    3
d    4
dtype: int64

In [210]:
s=pd.Series(np.array([1,2,3,4]),index=['a','b','c','d'])
s.shape
s.size

4

In [211]:
# cewating a series with the help of list
li=[1,2,3,4]
li_idx=['a','b','c','d']
pd.Series(li,index=li_idx)

a    1
b    2
c    3
d    4
dtype: int64

In [212]:
# creating the series with the help of dictionary
d={'a':10,'b':20,'c':30,'d':40}
pd.Series(d)
# when we create ny series with the help of dictionary
# key --> index , value--> value

a    10
b    20
c    30
d    40
dtype: int64

In [213]:
d={'a':10,'b':20,'c':30,'d':40}
s1=pd.Series(d)
s1.values
# .values is used to retrieve the values of the series
# it returns the values into the form of numpy array

array([10, 20, 30, 40])

In [214]:
# .index method is used to find all the indices of the series
s1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [215]:
s1.dtype

dtype('int64')

In [216]:
# vectorised operations ==>
s1=pd.Series([1,2,3,4])
s2=pd.Series([5,6,7,8])
s1+s2

0     6
1     8
2    10
3    12
dtype: int64

In [217]:
s1+1

0    2
1    3
2    4
3    5
dtype: int64

In [218]:
s1**2

0     1
1     4
2     9
3    16
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

# accessing the elements using indeces
series=pd.Series(np.arange(1,13))
# we can access the elements of the series using some coditions
series[series>5]

In [220]:
series[series%2==0]

NameError: name 'series' is not defined

In [221]:
# dataframes
# A pandas DataFrame is a primary two-dimensional, table-like data structure used for data manipulation and analysis in Python
# Data: The actual values stored within the table.
# Rows: labeled observations (also called the index )
# Columns: Labels that define each category or variable of data.

In [238]:
# creat dataframes with the help of dictionary
student_details ={'name':['rahul','aman','yash'],
                  'subject':['math','english','ss'],
                  'marks':[50,60,70],
                  'address':['jaipur','delhi','alwar']
                  }
pd.DataFrame(student_details,index=['a','b','c'])

name  subject  marks address
a  rahul     math     50  jaipur
b   aman  english     60   delhi
c   yash       ss     70   alwar

In [223]:
# creat dataframes with the help of list
student_details=[
    ['rahul','maths',50,'jaipur'],
    ['aman','english',60,'delhi'],
    ['yash','ss',70,'alwar']
]
pd.DataFrame(student_details,columns=['name','subject','marks','address'],index=['a','b','c'])

name  subject  marks address
a  rahul    maths     50  jaipur
b   aman  english     60   delhi
c   yash       ss     70   alwar

In [224]:
import pandas as pd
import numpy as np

In [225]:
# converting a dataframe to csv formate
student_details ={'name':['rahul','aman','yash'],
                  'subject':['math','english','ss'],
                  'marks':[50,60,70],
                  'address':['jaipur','delhi','alwar']}

df=pd.DataFrame(student_details,index=['a','b','c'])
df.to_csv('student_data.csv')


In [226]:
# converting a datafrane to csv formate
df.to_excel('student_data.xlsx')

In [227]:

# pandas -> read,csv,read_csv('path')
# write -> to_csv -> appky on the dataframe
# to_csv('filename.csv')

In [228]:
df=pd.read_csv('/content/sample_data/california_housing_train.csv')
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [229]:
df.columns
# df.columns-> gives the columns names which are present into the dataframe

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [230]:
# selecting the only one column from the dataframe
# df_name['column_name']
df['total_bedrooms']

0        1283.0
1        1901.0
2         174.0
3         337.0
4         326.0
          ...  
16995     394.0
16996     528.0
16997     531.0
16998     552.0
16999     300.0
Name: total_bedrooms, Length: 17000, dtype: float64

In [231]:
# selecting the multiple columns using the list of the column which you want show.
df[['total_bedrooms','longitude', 'latitude', 'housing_median_age', 'total_rooms']]

total_bedrooms  longitude  latitude  housing_median_age  total_rooms
0              1283.0    -114.31     34.19                15.0       5612.0
1              1901.0    -114.47     34.40                19.0       7650.0
2               174.0    -114.56     33.69                17.0        720.0
3               337.0    -114.57     33.64                14.0       1501.0
4               326.0    -114.57     33.57                20.0       1454.0
...               ...        ...       ...                 ...          ...
16995           394.0    -124.26     40.58                52.0       2217.0
16996           528.0    -124.27     40.69                36.0       2349.0
16997           531.0    -124.30     41.84                17.0       2677.0
16998           552.0    -124.30     41.80                19.0       2672.0
16999           300.0    -124.35     40.54                52.0       1820.0

[17000 rows x 5 columns]

In [232]:
# to select the first row of the dataframe
df.loc[0]

longitude              -114.3100
latitude                 34.1900
housing_median_age       15.0000
total_rooms            5612.0000
total_bedrooms         1283.0000
population             1015.0000
households              472.0000
median_income             1.4936
median_house_value    66900.0000
Name: 0, dtype: float64

In [234]:
# to select the first  row of the dataframe
#into this slicing the end included

# df.loc is used to retrive the row using the labels
df.loc[0:6], ['longitude', 'latitude', 'housing_median_age', 'total_rooms']
#

(   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 0    -114.31     34.19                15.0       5612.0          1283.0   
 1    -114.47     34.40                19.0       7650.0          1901.0   
 2    -114.56     33.69                17.0        720.0           174.0   
 3    -114.57     33.64                14.0       1501.0           337.0   
 4    -114.57     33.57                20.0       1454.0           326.0   
 5    -114.58     33.63                29.0       1387.0           236.0   
 6    -114.58     33.61                25.0       2907.0           680.0   
 
    population  households  median_income  median_house_value  
 0      1015.0       472.0         1.4936             66900.0  
 1      1129.0       463.0         1.8200             80100.0  
 2       333.0       117.0         1.6509             85700.0  
 3       515.0       226.0         3.1917             73400.0  
 4       624.0       262.0         1.9250             65500.0  
 5    

In [236]:
df.loc[0:6,['longitude', 'latitude', 'housing_median_age', 'total_rooms']]

longitude  latitude  housing_median_age  total_rooms
0    -114.31     34.19                15.0       5612.0
1    -114.47     34.40                19.0       7650.0
2    -114.56     33.69                17.0        720.0
3    -114.57     33.64                14.0       1501.0
4    -114.57     33.57                20.0       1454.0
5    -114.58     33.63                29.0       1387.0
6    -114.58     33.61                25.0       2907.0

In [241]:
tudent_details ={'name':['rahul','aman','yash'],
                  'subject':['math','english','ss'],
                  'marks':[50,60,70],
                  'address':['jaipur','delhi','alwar']
                  }
x = pd.DataFrame(student_details,index=['a','b','c'])

In [243]:
x.loc[['a','b','c'],['subject','marks']]

subject  marks
a     math     50
b  english     60
c       ss     70

In [244]:
# select all rows of the dataframe and also select three any columns
df.loc[:,['longitude', 'latitude', 'housing_median_age']]


longitude  latitude  housing_median_age
0        -114.31     34.19                15.0
1        -114.47     34.40                19.0
2        -114.56     33.69                17.0
3        -114.57     33.64                14.0
4        -114.57     33.57                20.0
...          ...       ...                 ...
16995    -124.26     40.58                52.0
16996    -124.27     40.69                36.0
16997    -124.30     41.84                17.0
16998    -124.30     41.80                19.0
16999    -124.35     40.54                52.0

[17000 rows x 3 columns]

In [ ]:
#.loc[]:---->
# The .loc property in pandas is used for label-based indexing,
#  allowing you to select data from a DataFrame using the specified row and column names (labels).
# # Key Features of .loc

#     Label-Based: You must use the actual names (labels) of the rows and columns,
#     not their integer positions.
#     Inclusive Slicing: Unlike standard Python slicing,
#     when you slice with .loc (e.g., df.loc['start_label':'end_label']),
#     both the start and end labels are included in the result.

In [245]:
df.iloc[0:4, 0:4]

longitude  latitude  housing_median_age  total_rooms
0    -114.31     34.19                15.0       5612.0
1    -114.47     34.40                19.0       7650.0
2    -114.56     33.69                17.0        720.0
3    -114.57     33.64                14.0       1501.0

In [246]:
 # df.iloc[] access the rows and columns based on integer positions of the row and columns
# into this the slicing is same the normal python slicing
# end -> exclusive
# sntax of iloc : df.iloc[row_slicing,colums_slicint]
df.iloc[0:4,0:4]


longitude  latitude  housing_median_age  total_rooms
0    -114.31     34.19                15.0       5612.0
1    -114.47     34.40                19.0       7650.0
2    -114.56     33.69                17.0        720.0
3    -114.57     33.64                14.0       1501.0